name: yahoo_finance
description: Unofficial library for using yahoo finance api
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.4
  pretty_dio_logger: ^1.1.1
  enum_to_string: ^2.0.1
